name: Build

on:
  # push代码时触发workflow
  push:
    # 忽略README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  # pull_request时触发workflow
  pull_request:
    # 忽略README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    # 更新子模块
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-toolchain
          msystem: mingw64
          release: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.11"
          host: "windows"
          target: "desktop"
          arch: "win64_mingw73"
          dir: "${{github.workspace}}/qt/"
          install-deps: "true"

      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -B '${{github.workspace}}'/build
      - name: Build
        run: cmake --build '${{github.workspace}}'/build --target CadenceLibQML
